name: mitk # you probably want to 'snapcraft register <name>'
base: core # the base snap is the execution environment for this snap
version: '2015.05.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Medical Imaging Interaction Toolkit (MITK) # 79 char long summary
description: |
  The Medical Imaging Interaction Toolkit (MITK) is a free open-source software
  system for development of interactive medical image processing software. MITK
  combines the Insight Toolkit (ITK) and the Visualization Toolkit (VTK) with
  an application framework. As a toolkit, MITK offers those features that are
  relevant for the development of interactive medical imaging software covered
  neither by ITK nor VTK.
icon: snap/local/mitk.png
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
- amd64

parts:
  desktop-qt5-mitk:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-commit: de8dc068a05d24cea5c0438863280ab641226570
    source-subdir: qt/
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
  mitk:
    # See 'snapcraft plugins'
    source: http://www.mitk.org/download/releases/MITK-2015.05/Linux/MITK-2015.5.0-linux64.tar.gz
    after: [desktop-qt5-mitk]
    plugin: nil
    override-build: |
      cp -r bin $SNAPCRAFT_PART_INSTALL/usr/lib/MITK-2015.5.0-linux64
    stage-packages:
      - libqt5gui5
      - libqt5svg5
      - libqt5widgets5
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5sql5
      - libqt5xml5
      - libqt5sql5-sqlite
      - libqt5help5
      - libqt5webkit5
      - libxt6

  wrapper:
    plugin: dump
    after: [mitk]
    source: snap/local/
    organize:
      mitk-snap-wrapper.sh: usr/bin/mitk-snap-wrapper.sh
      mitk.desktop: usr/share/applications/mitk.desktop
      mitk.png: usr/share/icons/hicolor/48x48/apps/

apps:
  mitk:
    desktop: usr/share/applications/mitk.desktop
    command: desktop-launch $SNAP/usr/bin/mitk-snap-wrapper.sh
    plugs:
      - home
      - opengl
      - mount-observe
      - optical-drive
      - removable-media
      - x11
      - desktop
      - desktop-legacy
